# Generated by Django 4.0.3 on 2022-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='dateCreation_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dateCreation_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
